defaults:
  - model: Llama-3.2-1B-Instruct
  - collator: DataCollatorForSupervisedDatasetwithIndex
  - hydra: default
  - paths: default
  - _self_
  - experiment: null

seed: 0
mode: selective_prepare
task_name: selective_prepare
trainer:
  handler: selective_prepare
method: NPO
beta: 0.1
batch_size: 8
reference_manifest_path: ???
score_output_path: ${paths.output_dir}/difficulty.json

data: ???
