# @package eval.rwi.metrics.forget_Q_A_token_Prob
defaults:
  - ../../data/datasets@datasets: RWI_QA_forget
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: token_probability
batch_size: ${eval.rwi.batch_size}

datasets:
  RWI_QA_forget:
    args:
      hf_args:
        name: forget
