# @package eval.rwi.metrics.retain_Q_A_Prob
defaults:
  - ../../data/datasets@datasets: RWI_QA_retain_golden
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: probability
batch_size: ${eval.rwi.batch_size}
